### ISSUE TITLE
Conversion to bytes fails for signed integers

### ISSUE THREAD

**Issue by Dobatymo** [AlexAltea/htypes#9]
https://github.com/AlexAltea/ntypes/blob/27cf3aa76457a5890092bc347775d7f1bd982eee/nativetypes/native_int.py#L94

needs a signed=True argument https://docs.python.org/3/library/stdtypes.html#int.to_bytes

**Comment by AlexAltea** [comment]
Thanks. Fixed in https://github.com/AlexAltea/ntypes/commit/cc958e6bedbb19d42f5ec0cdca37b9f31ee8d584.

Available on `v1.0.5` at https://pypi.org/project/nativetypes/.

**Comment by AlexAltea** [comment]
EDIT: Bumped to `v1.0.6`, since `v1.0.5` was a botched release.
